version: '2'

services:
  webserver:
    build: ./docker/webserver
    image: runwaytest_web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src/app:/var/www/html
    links:
      - db

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=test

version: '3.5'

services:
  app:
    container_name: p2-app
    image: php:5.6-apache
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src/app:/var/www/html
    links:
      - mariadb

  mariadb:
    container_name: p2-mariadb
    image: mariadb
    volumes:
#      - ./docker/var/lib/mysql:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  phpmyadmin:
    container_name: p2-phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
    ports:
      - 8080:80