version: '3.5'

services:
  app:
    container_name: p2-app
    image: josephmart/php56
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src/app:/var/www/html
    depends_on:
      - mariadb
    environment:
      MYSQL_IP: mariadb
      DEV: 1

  mariadb:
    container_name: p2-mariadb
    image: mariadb
    volumes:
#      - ./docker/var/lib/mysql:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: josephmart
      MYSQL_USER: josephmart
      MYSQL_PASSWORD: martinsen
    ports:
      - 3306:3306

  phpmyadmin:
    container_name: p2-phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
    ports:
      - 8080:80